const subtitles = {
    kr: [
      { time: 0.6, end: 3, text: '.오, 뭐야!' },
      { time: 4, end: 7, text: '.안녕~' },
      { time: 8, end: 13, text: '.잘 들린다면 하트를 눌러주세요옹' },
      { time: 17, end: 20, text: '.들린다면 하트를 눌러줘~' },
      { time: 20, end: 23, text: '.오! 이거 뭐야!?' },
      { time: 28.5, end: 31, text: '.오!' },
      { time: 33, end: 35, text: '.오! 또 뭐 없나?' },
      { time: 35, end: 37.5, text: '.또 뭐 있어요?' },
      { time: 39.5, end: 41.5, text: '.뭐가 있을까?' },
      { time: 45, end: 47, text: '.오!' },
      { time: 51, end: 53, text: '.이건 없나?' },
      { time: 53.2, end: 54, text: '.오!' },
      { time: 54.5, end: 56, text: '.뭐야 나 성공률 뭐야!?' },
      { time: 56.2, end: 57, text: '.잠깐만 잠깐만!' },
      { time: 57.6, end: 61, text: '.또 빨리 알려줘' },
      { time: 64, end: 66, text: '.아 이건 안되네' },
      { time: 66.1, end: 69, text: '.브이 해봤어, 브이 했어요..' },
      { time: 70, end: 74, text: '.다른거 없어? 끝이야? 나 다했어?' },
    ],
    en: [
      { time: 0.6, end: 3, text: ".Oh!" },
      { time: 4, end: 7, text: ".Hi~" },
      { time: 8, end: 13, text: ".If you can hear me, please press the like button" },
      { time: 17, end: 20, text: ".If you can hear me, press the like~" },
      { time: 20, end: 23, text: ".Oh! What's this!?" },
      { time: 28.5, end: 31, text: ".Oh!" },
      { time: 33, end: 35, text: ".Oh! Is there any other things?" },
      { time: 35, end: 37.5, text: ".anything else?" },
      { time: 39.5, end: 41.5, text: ".Then what about this" },
      { time: 45, end: 47, text: ".Oh!" },
      { time: 51, end: 53, text: ".Is that ok?" },
      { time: 53.2, end: 54, text: ".Oh!" },
      { time: 54.5, end: 56, text: ".What? What's my success rate" },
      { time: 56.2, end: 57, text: ".Wait, wait!" },
      { time: 57.6, end: 61, text: ".Tell me another one guys~" },
      { time: 64, end: 66, text: ".Ah, it doesn’t work" },
      { time: 66.1, end: 69, text: ".I Tried V sign, I already did it.." },
      { time: 70, end: 74, text: ".Nothing else? I did them all?" },
    ],
    jp: [
      { time: 0.6, end: 3, text: ".あれ、何これ！" },
      { time: 4, end: 7, text: ".こんにちは〜" },
      { time: 8, end: 13, text: ".聞こえてたらハートを押してね" },
      { time: 17, end: 20, text: ".聞こえるならハート押して〜" },
      { time: 20, end: 23, text: ".わぁ！これ何！?" },
      { time: 28.5, end: 31, text: ".わぁ！" },
      { time: 33, end: 35, text: ".わぁ！他に何かある？" },
      { time: 35, end: 37.5, text: ".他に何かありますか？" },
      { time: 39.5, end: 41.5, text: ".何があるかな？" },
      { time: 45, end: 47, text: ".わぁ！" },
      { time: 51, end: 53, text: ".これないの？" },
      { time: 53.2, end: 54, text: ".わぁ！" },
      { time: 54.5, end: 56, text: ".えっ、私の成功率何！？" },
      { time: 56.2, end: 57, text: ".ちょっと待って、ちょっと待って！" },
      { time: 57.6, end: 61, text: ".また早く教えて" },
      { time: 64, end: 66, text: ".あ、これはダメね" },
      { time: 66.1, end: 69, text: ".Vサインしてみた、やったよ…" },
      { time: 70, end: 74, text: ".他にないの？終わり？全部やった？" },
    ],
    cn: [
      { time: 0.6, end: 3, text: ".哦，来了！" },
      { time: 4, end: 7, text: ".你好~" },
      { time: 8, end: 13, text: ".如果听得见请按下点赞" },
      { time: 17, end: 20, text: ".听得见的话按一下比心~" },
      { time: 20, end: 23, text: ".哇！这是什么！?" },
      { time: 28.5, end: 31, text: ".哇！" },
      { time: 33, end: 35, text: ".哇！还有别的吗？" },
      { time: 35, end: 37.5, text: ".还有什么？" },
      { time: 39.5, end: 41.5, text: ".考虑一下有没有别的" },
      { time: 45, end: 47, text: ".哇！" },
      { time: 51, end: 53, text: ".这个没有吗？" },
      { time: 53.2, end: 54, text: ".哇！" },
      { time: 54.5, end: 56, text: ".你看我的成功率多高哈哈哈" },
      { time: 56.2, end: 57, text: ".等一下 等一下！" },
      { time: 57.6, end: 61, text: ".快来教我别的" },
      { time: 64, end: 66, text: ".啊，这个不行啊" },
      { time: 66.1, end: 69, text: ".早就试过 已经试过" },
      { time: 70, end: 74, text: ".没有别的吗？结束了？我都做完了吗？" },
    ]
  };
  
  export default subtitles;
  